version: "3.7"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/Jellyseerr:/app/config
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    privileged: true
    group_add:
      - "122"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${PUBLIC_IP}
    volumes:
      - ${CONFIG_PATH}/Jellyfin:/config
      - ${MEDIA_PATH}/Media/tvseries:/data/tvshows
      - ${MEDIA_PATH}/Media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    devices: # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Bazarr:/config
      - ${MEDIA_PATH}/Media/movies:/movies #optional
      - ${MEDIA_PATH}/Media/tvseries:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Sonarr:/config
      - ${MEDIA_PATH}/Media/tvseries:/tv #optional
      - ${MEDIA_PATH}/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Radarr:/config
      - ${MEDIA_PATH}/Media/movies:/movies #optional
      - ${MEDIA_PATH}/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}/qBittorrent:/config/qBittorrent
      - ${MEDIA_PATH}/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: unless-stopped

  httpd:
    image: httpd:latest
    container_name: httpd
    ports:
      - "80:80"
    volumes:
      - ${CONFIG_PATH}/Httpd:/usr/local/apache2/htdocs
    restart: unless-stopped

  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - 800:8080
    volumes:
      - /home/${USER}:/data/Home
      - ${MEDIA_PATH}:/data/"Media Files"
      - ${CONFIG_PATH}:/data/"Config Files"
    restart: unless-stopped
